### PR TITLE
DIABLO-281, if course is 'approved' by admin only then it will not show on partially-approval list

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/DIABLO-281

### CODE REVIEW

**Comment by paulkerschen** [comment]
@johncrossman I think this SQL change would screen out any course that is approved by an admin and no instructors, but it would not screen out any course that was approved by 1) an admin; and 2) some but not all instructors. For consistency's sake it seems like if we're going to screen out the first type, we should also screen out the second, which might require filtering against a subquery to fetch all admin approvals for the term.

**Comment by johncrossman** [comment]
@paulkerschen - What you describe was my intention: the 'Partially Approved' list should include _all_ courses (scheduled and not scheduled) that were approved by "some but not all instructors",  regardless of admin approval or none. Now I could be wrong. :)  I assumed this change met the reqt described by Willa in https://jira.ets.berkeley.edu/jira/browse/DIABLO-175

**Comment by paulkerschen** [comment]
@johncrossman Ah, I see what you’re saying. Maybe we had better review requirements on Monday? I didn’t have a chance to document Friday’s reqs conversation in JIRA, and I too might have misunderstood, but I had thought we clarified/superseded DIABLO-175 by specifying that admin approval should always remove a course from the “Partially Approved” filter. We would then expect it to show up under “Queued for Scheduling” or “Scheduled.”

**Comment by paulkerschen** [comment]
Requirements are in. Thanks for confirming, @johncrossman.

**Pull request merged**
